
# MCU name
MCU = RP2040

# Bootloader selection
BOOTLOADER = rp2040
SERIAL_DRIVER = vendor

# Via/Vial
VIA_ENABLE = yes

VIALRGB_ENABLE = yes
OLED_DRIVER = ssd1306
RGB_MATRIX_ENABLE = yes

# Setup neaded features
KEY_OVERRIDE_ENABLE = no
TAP_DANCE_ENABLE = no
COMBO_ENABLE = no

OLED_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
WPM_ENABLE = yes
GRAVE_ESC_ENABLE = yes
MAGIC_ENABLE = yes
BOOTMAGIC_ENABLE = yes

JOYSTICK_ENABLE = yes
JOYSTICK_DRIVER = analog


ENCODER_MAP_ENABLE = yes
ENCODER_ENABLE = yes
NKRO_ENABLE = no

COMMAND_ENABLE = yes
CONSOLE_ENABLE = yes

QMK_SETTINGS = yes
LTO_ENABLE = yes



# Deprecated features
# DEFAULT_FOLDER = lily58_my/pandakb
# VIAL_ENABLE = yes

